### ISSUE TITLE
No response from mech status request

### ISSUE THREAD

**Issue by kons-9** [CANDY-HOUSE/Sesame_BluetoothAPI_document#10]
Hi, thanks for great products! I am using SESAME5 and I would like to get mechStatus.

I sent a mechStatus request according to the [documentation link](https://github.com/CANDY-HOUSE/Sesame_BluetoothAPI_document/blob/master/SesameOS3/sesame_ble_cmd.md#32-request-%E8%B3%87%E6%96%99%E6%A0%BC%E5%BC%8F), but I could not get a response.
And also, I found that in [detailed document](https://github.com/CANDY-HOUSE/Sesame_BluetoothAPI_document/blob/master/SesameOS3/item_details/81_mechStatus.md), mechStatus does not have any request commands.

For context, I am able to get responses for such as lock/unlock/magnet etc. So, I guess the connection is established correctly.

My question are:
* which document is true?
* is there any way to get mechStatus, and if so, how to get it?

**Comment by zhouxingchun** [comment]
Hi,  can you tell  whicth platform OS you use to connect SESAME5.

[Documents](https://document.candyhouse.co/demo/bluetooth-en#application-layer-business-content) here to guide how to establish an effective connection.

When  Sesame is registered or logged in successfully. mechStatus will publish automatically. SSM2_OP_CODE_PUBLISH = 0x08.

**Comment by kons-9** [comment]
thanks for replying!
> When Sesame is registered or logged in successfully. mechStatus will publish automatically. SSM2_OP_CODE_PUBLISH = 0x08.

As you said, I can get it when logging in, but I would like to know mechStatus of already logged or registered Sesame5.

According to ble cmd documentation, sesame can receive mechStatus request, so I thought I can get mechStatus at any time I request it. But when I did it, sesame didnot reply any responses.

Is there any way to get mechsatatus proacitively?

**Comment by zhouxingchun** [comment]
In order to prevent the client from frequently requesting the mechanical status from sesame5, sesame5 can only actively send it when the mechanical status changes.

**Comment by kons-9** [comment]
OK, I understand. Thanks!
